name: frappe_dart
description: A frappe api wrapper.
version: 0.0.1
homepage: https://github.com/kinetsystems/frappe_dart
repository: https://github.com/kinetsystems/frappe_dart
publish_to: https://pub.dev/packages/frappe_dart
issue_tracker: https://github.com/kinetsystems/frappe_dart/issues
topics:
  - frappe
  - api



environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0

