name: frappe_dart
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
homepage: https://github.com/kinetsystems/frappe_dart
repository: https://github.com/kinetsystems/frappe_dart
publish_to: https://pub.dev/publishers/kinetsystems.com
issue_tracker: https://github.com/kinetsystems/frappe_dart/issues
topics:
  - frappe
  - api



environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
dependencies:
  http: ^1.2.2
  equatable: ^2.0.7
